# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# prefix: Ctrl-Space
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# general
set -g mouse on
set -g history-limit 50000
set -sg escape-time 10
set -g renumber-windows on
set -g base-index 0
setw -g pane-base-index 0

# splits keep current working directory
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# copy mode: vi keys, v to select, y to yank to system clipboard
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"

# status bar
## general
set -g status on
set -g status-position bottom
set -g status-interval 60
set -g status-style "bg=yellow fg=black,bold"

## left
set -g status-left-length 100
set -g status-left "[pane:#P | win:#W | sess:#S] "

## status list
set -g window-status-format "#F"
set -g window-status-current-format "#F"

## right
set -g status-right "%H:%M %d-%b-%y"

# pane borders
set -g pane-border-style "fg=brightblack, bold"
set -g pane-active-border-style "fg=yellow,bold"
set -g pane-border-lines double
set -g pane-border-status top
set -g pane-border-format " PANE-#P: #{pane_current_command} | #{pane_current_path} "

# pane create
bind v split-window -h
bind s split-window -v

# pane navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# pane kill
bind x kill-pane

# list sessions
bind Tab choose-tree -Zs
